CREATE TABLE audit_logs
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id BIGINT                                  NOT NULL,
    entity_type     VARCHAR(50)                             NOT NULL,
    entity_id       BIGINT                                  NOT NULL,
    action          VARCHAR(50)                             NOT NULL,
    old_value       TEXT,
    new_value       TEXT,
    performed_by    BIGINT                                  NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

CREATE TABLE comments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id BIGINT                                  NOT NULL,
    task_id         BIGINT                                  NOT NULL,
    author_id       BIGINT                                  NOT NULL,
    text            TEXT                                    NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

CREATE TABLE organizations
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_organizations PRIMARY KEY (id)
);

CREATE TABLE projects
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id BIGINT                                  NOT NULL,
    created_by      BIGINT                                  NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    description     TEXT,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE TABLE refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    token      VARCHAR(500)                            NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    revoked    BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

CREATE TABLE tasks
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id BIGINT                                  NOT NULL,
    project_id      BIGINT                                  NOT NULL,
    assignee_id     BIGINT,
    reporter_id     BIGINT                                  NOT NULL,
    title           VARCHAR(255)                            NOT NULL,
    description     TEXT,
    status          VARCHAR(30)                             NOT NULL,
    priority        VARCHAR(30)                             NOT NULL,
    due_date        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

CREATE TABLE users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id BIGINT                                  NOT NULL,
    first_name      VARCHAR(100)                            NOT NULL,
    last_name       VARCHAR(100)                            NOT NULL,
    email           VARCHAR(255)                            NOT NULL,
    password        VARCHAR(255)                            NOT NULL,
    role            VARCHAR(30)                             NOT NULL,
    active          BOOLEAN                                 NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE organizations
    ADD CONSTRAINT uc_organizations_name UNIQUE (name);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_token UNIQUE (token);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE audit_logs
    ADD CONSTRAINT FK_AUDIT_LOGS_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id);

ALTER TABLE audit_logs
    ADD CONSTRAINT FK_AUDIT_LOGS_ON_PERFORMED_BY FOREIGN KEY (performed_by) REFERENCES users (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_TASK FOREIGN KEY (task_id) REFERENCES tasks (id);

ALTER TABLE projects
    ADD CONSTRAINT FK_PROJECTS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE projects
    ADD CONSTRAINT FK_PROJECTS_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_ASSIGNEE FOREIGN KEY (assignee_id) REFERENCES users (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_REPORTER FOREIGN KEY (reporter_id) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id);